--- 
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql 
    env: dev
spec:
  containers:
  - name: mysql
    image: mysql:8.0-debian
    resources: 
      limits: 
        cpu: "500m"
        memory: "64Mi" 
    env: 
      - name: MYSQL_ROOT_PASSWORD
        value: Krishna0527@
      - name: MYSQL_DATABASE
        value: test
      - name: MYSQL_USER
        value: gopi
      - name: MYSQL_PASSWORD
        value: Krishna0527@     
---
apiVersion: v1
kind: Pod
metadata:
  name: postgress
  labels:
    name: postgress
spec:
  containers:
  - name: postgress
    image: postgres:alpine3.19
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env: 
      - name: POSTGRES_USER
        value: gopi
      - name: POSTGRES_HOST
        value: gopi
      - name: POSTGRES_DB
        value: test
      - name: POSTGRES_PASSWORD
        value: Krishna0527@ ##kubectl exec --stdin --tty postgress -- /bin/bash
    
    postgres:
      - containerPort: 52



      
      
